XiangXiang/XiangXiang/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using XiangXiang.Models;

namespace XiangXiang.Controllers
{
    public class SupplierController : Controller
    {
        private readonly dbXContext _conetxt;
        public SupplierController(dbXContext conetxt)
        {
            _conetxt = conetxt;
        }
        public IActionResult List()
        {
            IEnumerable<TSupplier> data=null;
            dbXContext db = new dbXContext();
            data = from t in _conetxt.TSuppliers
                   select t;
            return View(data);
        }

        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create(TSupplier p)
        {
            dbXContext db = new dbXContext();
            _conetxt.TSuppliers.Add(p);
            _conetxt.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Edit(TSupplier p)
        {
            dbXContext db = new dbXContext();
            TSupplier x = _conetxt.TSuppliers.FirstOrDefault(t => t.SupplierId == p.SupplierId);
            if (x != null)
            {

                x.Name = p.Name;
                x.Email = p.Email;
                x.Phone = p.Phone;
                x.Password = p.Password;
                x.Address = p.Address;
                x.CreditPoints = p.CreditPoints;
                _conetxt.SaveChangesAsync();

            }
            return RedirectToAction("List");
        }
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                dbXContext db = new dbXContext();
                TSupplier x = _conetxt.TSuppliers.FirstOrDefault(t => t.SupplierId == id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                dbXContext db = new dbXContext();
                TSupplier delSupplier = _conetxt.TSuppliers.FirstOrDefault(t => t.SupplierId == id);
                if (delSupplier != null)
                {
                    _conetxt.TSuppliers.Remove(delSupplier);
                    _conetxt.SaveChangesAsync();
                }
            }
            return RedirectToAction("List");
        }

    }
}

XiangXiang/XiangXiang/Views/Supplier/Create.cshtml
@model XiangXiang.Models.TSupplier

@{
    ViewData["Title"] = "供應商註冊系統";
}

<h1>供應商註冊系統</h1>

<h4>請輸入資訊</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" value=100 name="CreditPoints" />
 
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="註冊" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">取消</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

XiangXiang/XiangXiang/Views/Supplier/Edit.cshtml
@model XiangXiang.Models.TSupplier

@{
    ViewData["Title"] = "修改業者作業";
}



<h1>修改業者作業</h1>

<h4>請輸入要修改的資料</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="SupplierId" value="@Model.SupplierId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditPoints" class="control-label"></label>
                <input asp-for="CreditPoints" class="form-control" />
                <span asp-validation-for="CreditPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlackListed" class="control-label"></label>
                <input asp-for="BlackListed" class="form-control" />
                <span asp-validation-for="BlackListed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="確認修改" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">取消</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

XiangXiang/XiangXiang/Views/Supplier/List.cshtml
@model IEnumerable<XiangXiang.Models.TSupplier>

@{
    ViewData["Title"] = "List";
}

<h1>業者資料一覽表</h1>

<div class="x_content">
    <p>
        <a asp-action="Create">新增客戶</a>
    </p>
    <table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
               序
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlackListed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
            foreach (var item in Model) {
                count++;


        <tr>
            <td>
                @count
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlackListed)
            </td>
            <td>
                 @Html.ActionLink("修改", "Edit", new { id=item.SupplierId}) |
                 @Html.ActionLink("刪除", "Delete","Supplier", new {id=item.SupplierId},new{onclick="return confirm('確定要刪除嗎?')"})
            </td>
        </tr>
}
}
    </tbody>
</table>
</div>